### ISSUE TITLE
About section

### ISSUE THREAD

**Issue by bensley** [thinkshout/redhencrm.com#6]
Change the About section so that it says Blog.  Remove About RedHen and following paragraph into a footer section.

**Comment by nadavoid** [comment]
@bensley So the About paragraph (starting with "RedHen CRM is a project of...") should go into a footer section. There is not currently a footer section, so should this new footer section just go directly under the Get the Code section, and is accessible only by scrolling down to the very bottom of the page?

**Comment by bensley** [comment]
Correct.  Thanks for updating.
